on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Lint PHP files
        run: |
          set -e  # Exit on any error
          failed=0
          for file in $(find . -name "*.php"); do
            echo "Linting $file"
            php -l "$file" || failed=1
          done
          exit $failed
